### ISSUE TITLE
Can't install?

### ISSUE THREAD

**Issue by CatharsisFonts** [Tosche/Alcarin-Tengwar#1]
Hi Tosche,

thanks for your beautiful font! However, I haven't been able to install either the TTFs or the OTFs. I drag them into Fontbook, the «adding fonts...» dialog briefly pops up, then nothing happens. I can't see Alcarin in the list of installed fonts. Perhaps it has to do with Latin not being present?

Cheers, Christian

**Comment by Tosche** [comment]
I guess I need to add some Latin glyphs in this case. There are plenty of system fonts without Latin, but I think the font has to be able to display its name in the intended script. Since this is for a fictional script, there is no way to fix that by editing the metadata. (I didn't have this problem as I was using a font manager app)

**Comment by Tosche** [comment]
Added Noto Serif ASCII set.
