### ISSUE TITLE
Right-to-left numerals

### ISSUE THREAD

**Issue by skalyan91** [Tosche/Alcarin-Tengwar#5]
Apparently in Tengwar, numerals are supposed to be written from right to left (similarly to how in Arabic, numerals are written from left to right even though text goes from right to left); see http://fan.theonering.net/~rolozo/tengwar/tengwar/numbers.htm. I wonder if it would be possible to mark the Tengwar digits as RTL glyphs.

**Comment by Tosche** [comment]
Done. Also, I've set the Rumilian numerals to bidirectional for the time being until we have more info.

**Comment by arnog** [comment]
Hmmm… that’s a bit of a problem because now the encoding is no longer compatible with the Telcontar encoding (when generating output for numerals, the order of the code points have to be reversed).

**Comment by Tosche** [comment]
To me, that sounds like an old workaround when RTL text processing was not reliable (it has other minor-level behaviour inconsistencies with Telcontar anyway). I don't know what to do though; I could mark all numerals as bidirectional, and add RTL signifier glyph, but would that be enough?

**Comment by arnog** [comment]
Yes, marking them bidi would be better.

There are two issues:

- compatibility with Telcontar (marking those codepoints as RTL render Alcarin incompatible with Telcontar, because software (e.g. Tecendil) that outputs Tengwar would need to know if the digits are marked LTR or not to output the correct sequence of codepoints.

- if Telcontar and Alcarin were using the same marking for numerals, what should it be? Personally, I would find marking numerals RTL to be unexpected (it would mostly affect the behavior of text editors when navigating with arrow keys), since Tengwar in general is a LTR script and directionality typically affects an entire script, not some characters within a script. Furthemore, while numeral Tengwar are frequently written with the least significant digit first, this is not strictly speaking *required*. This is why the LSB dot glyph exist: to indicate if a given number is written using LSB first or not.

**Comment by skalyan91** [comment]
Re “directionality typically affects an entire script, not some characters within a script”: this is false for Arabic, as I mentioned above (numbers are LTR, even though text is RTL). Given that Tengwar is already like Arabic in other respects (notably in being an abjad), I wouldn’t find the mixing of directionality unexpected.

I’m not convinced that compatibility with Telcontar is a valid issue here; Telcontar doesn’t even have proper numerals (the numerals it provides are just copied from FreeMonoTengwar). In fact, I think there’s an argument to be made that Alcarin should set the standard for all future Unicode Tengwar fonts (including, hopefully, future versions of Telcontar).

**Comment by skalyan91** [comment]
@Tosche Numerals still seem to be LTR (at least in TextEdit on macOS Catalina). Maybe this is just a Mac issue?

**Comment by Tosche** [comment]
I would agree with Siva's argument. I actually found that all Tengwar fonts, including Telcontar, already have the numerals set as RTL.

As for the issue of font seemingly behaving as before, I think that's Mac's font cache issue since all updated fonts have the identical name. I want to refrain from adding version numbers or dates to the family name, but will probably have to do so to avoid inconvenience.

**Comment by Tosche** [comment]
I am still unclear about the Rumilian numerals' direction, so I'll leave them bidirectional for now.

**Comment by Tosche** [comment]
It appears that Glyphs ignores writing direction flag in the numerals. They are LTR for now until the app gets updated.

**Comment by Tosche** [comment]
I was told the fonts do not dictate the writing direction; the Unicode properties and layout engines do. There is nothing more that I need to do on this front.
